### ISSUE TITLE
[Feat] 바코드 인식 페이지

### ISSUE THREAD

**Issue by simeunseo** [RedCross-Revive-Hackthon/frontend#19]
## 🛠 Issue

바코드 인식 페이지를 구현한다.

## 📝 To-do

- [x] 바코드 인식기능 구현
- [x] 플러스 버튼에 바코드 인식 페이지 연결
- [x] 바코드 인식 결과 처리
